apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: escluster
spec:
  version: 7.8.0
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
      # xpack.security.enabled: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms512m -Xmx512m"
              - name: "xpack.monitoring.collection.enabled"
                value: "true"
            resources:
              requests:
                cpu: "500m"
                memory: "600Mi"
        initContainers:
        - name: install-kuromoji
          command:
          - "sh"
          - "-c"
          - "bin/elasticsearch-plugin install --batch analysis-kuromoji"
        # Schedule pods as distributed ristricly
        #   https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: escluster
              topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
